#!/bin/bash

# Purpose: 
#   Collect backup files from webservers by pulling from remote servers
#   Copy and rename files locally to match the retention scheme
#   Rotate and remove files falling out of the retention period
#
# Guidelines:
#   Each backup file is to be a single archived and compressed file containing
#   all files deemed relevant by the webmaster
#
#   Files will be retrieved via scp or sftp
#   Retrieval must use a asymmetric key pair

# Each server listed here must be:
#   Added to the serverNameToIP array
#   Added to the serverNameToUsername array
#   Added to the case statement in main ()
# 
# Each site, on each <<servername>> must be:
#   Added as a variable: <<servername>>Sites to enumerate the websites to back up
#   Ex: dev01Sites = ("amm" "fft")
#   Configured in the script on the target server
#   Must create directories on backup destination

__LOGLEVEL=4

declare -A logNameToLevel
logNameToLevel=([crit]="1" [error]="2" [warn]="3" [info]="4" [debug]="5")

function .log () {
    local levelName=${1};
    local level=${logNameToLevel[${levelName}]};

    # this moves the parameter numbers;
    shift;
    if [[ ${__LOGLEVEL} -ge ${level} ]]; then
        echo -e "[${levelName}]" "$@";
    fi;
}

test=0

regularLogDir="/var/log/scriptedBackups"

if [[ $1 == "-t" ]]; then
    test=1;
    echo "Test flag found."
    
    logFilePath=/home/$USER/scripts/webserverBackups-collect/logFile
    .log debug "Basic check for argument found test flag"

else
    if ! [[ -d "$regularLogDir" ]]; then
        mkdir "$regulardLogDir" || echo "failed to create $regularLogDir"; exit 1
    fi
    logFilePath="${regularLogDir}/scriptedBackup.log"

fi

exec 1>>${logFilePath}
exec 2>>${logFilePath} 

timeStamp=$(date +%Y%m%0d-%H:%M:%S)
.log crit "\n===Beginning of script run==="
.log crit "${timeStamp}"

declare srcServerNames

# Until the cursos site moves away from GoDaddy we must trigger
# the archiving script from here and wait for it to complete
sleepTime=180

# Must manually add/remove servers
srcServerNames=("dev01" "doweb01" "lm" "amm_prod_web_01" "gd_prod_web_02")
#srcServerNames=("lm")
.log debug "List of servers to pull from: ${srcServerNames[@]}"

# Declaring this is important because later indexing from the array doesn't get the right value otherwise
declare -A serverNameToIP
declare -A serverNameToUsername

# Must manually add/remove servers
serverNameToIP=([dev01]="172.16.208.18" [doweb01]="138.68.22.173" [lm]="198.71.227.7" [amm_prod_web_01]="172.16.208.20" [gd_prod_web_02]="166.62.108.22");
serverNameToUsername=([dev01]="backupadmin" [doweb01]="backupadmin" [lm]="fftlifestyle" [amm_prod_web_01]="backupadmin" [gd_prod_web_02]="i4843259938378");

cursosFileNamePath="/home/$USER/scripts/webserverBackups-collect/.cursos"

# Must manually add/remove sites you wish to back up
# Any new sites need to be added to the case statement near the end of the script
doweb01Sites=("mam")
dev01Sites=("mam")
lmSites=("lm")
amm_prod_web_01Sites=("amm" "fft" "ltr")
gd_prod_web_02Sites=("cursos")

identityFilePath="/home/$USER/.ssh/id_rsa"

currentDate="$(date +%Y%m%0d)"
currentYear="$(date +%Y)"
currentMonth="$(date +%m)"
currentDay="$(date +%0d)"

maxYears=6

oldestYear=$(expr $currentYear - $maxYears)

maxMonths=12 # This doesn't actually do anything. The number of months to use 
             #is set in the for loop within monthly_rotation ()

destDir="/storage/website_backups/"
oldDir="/storage/website_backups/removedBackups/"

for i in "$destDir" "$oldDir"; do
    if ! [[ -d "$i" ]]; then
        mkdir "$i" || echo "failed to create $i"; exit 1
    fi
done

fileExtension=".tar.gz"

is_directory () {
    # Return when the argument is longer than 0 and a valid directory
    # exit if not
    # Argument: $1 -> path

    path="${1}";
    .log debug "Beginning of is_directory ()";
    .log debug "Testing ${path}";

    if [[ -z "${path}" ]]; then
        .log crit "FAILED: is_directory () :: received argument of length 0";
        exit 1;
    elif [[ ! -d "${path}" ]]; then
        .log error "is_directory () :: ${path} is not a valid directory";
        .log info "${path} not found. Attempting to create ${path}";
        mkdir -p "${path}";
        if [[ $? != 0 ]]; then
            .log crit "FAILED: Creating ${path} was unsuccessful. Exiting.";
            exit 1;
        fi
    else
        .log debug "Success: is_directory (${path}) found ${path}";
        .log debug "Returning from is_directory ()";
    fi;
}

list_files () {
    # Return a list of files for the specified directory
    #
    # Arguments: $1 -> a directory path
    
    # .log debug "Beginning of list_files ()";
    is_directory $1;
    ls $1;
   

}

count_files () {
    # Return the number of files in a directory matching a specified backup
    # category
    #
    # Arguments: $1 -> a directory path
    #            $2 -> file backup category; one of ( daily | monthly | yearly )

    path=${1};
    keyword="${2}";

    # For some reason the script cannot make this log entry
    #.log debug "Starting count_files ()";

    if [[ -z "${keyword}" ]]; then
        .log crit "FAILED: count_files () :: Received invalid argument: $2";
        exit 1;

    else
        category=${2}
        case ${category} in 
            daily)
                value="$(ls $1 | grep -i daily | wc -l)";
                echo "${value}";
                ;;
            monthly)
                ls $1 | grep -i monthly | wc -l;
                ;;
            yearly) 
                ls $1 | grep -i yearly | wc -l;
                ;;
                
            *)
                .log crit "FAILED: count_files:case :: Received invalid argument: $2";
                exit 1;
                ;;
        esac;
    fi; 
}

daily_rotation () {
    # Remove files older than 7 days from a directory
    #
    # Arguments: $1 -> a directory path
    path=${1};
    .log info "Beginning daily_rotation ()";
    .log debug "Target path for daily_rotation ():${path}";
    
    keyword="daily";

    fileCount=$(count_files ${path} ${keyword});
   
    .log info "Initial number of ${keyword} files: ${fileCount}";

    if [[ "${fileCount}" -ge 7 ]]; then
        .log debug "Find files older than ${currentDate} - 7 days";
        .log debug "$(find ${path} -mtime +7 -iname "*daily*")";
        
        #.log info "Old $keyword files ''deleted'' to ${oldDir}";
        #find ${path} -mtime +7 -iname "*daily*" -exec mv '{}' ${oldDir} \; ;

        .log info "Removing old $keyword files";
        find ${path} -mtime +7 -iname "*daily*" -exec rm '{}' \; ;
        
    fi;
     
    
    fileCount=$(count_files $path $keyword);
    .log info "Ending number of $keyword files: $fileCount";
    .log info "$(ls -lh $path | grep $keyword)";
    .log debug "Returning from daily_rotation ()";

}

monthly_rotation() {
    # Remove files older than 6 months from a directory
    # For younger than 6 months, remove all but the oldest file for that month
    #
    # Arguments: $1 -> a directory path

    .log info "Beginning monthly rotation ()";

    path=${1};

    keyword=monthly

    fileCount=$(count_files $path $keyword);
    
    .log info "Initial number of $keyword files: $fileCount";

    .log debug "$(ls -lh ${path} | grep $keyword)";

    .log debug "Finding files older than $(expr 346 / 30 ) months";

    # Using +346 to catch files from the previous year/current month
    find ${path} -mtime +346 -iname "*monthly*" -exec rm '{}' \;

    # Important to only select files of the monthly category
    unsortedArray=($(find ${path} -iname "*monthly*" -printf "%TY,%Tm,%Td,%T@,%p\n"))
    sortedByYear=($(echo "${unsortedArray[@]}" | tr " " "\n" | sort | tr " " "\n"))

    activeYear=$currentYear
    activeMonth=$currentMonth
    
    # This range sets how many months to count back
    for i in {0..11}; do
        activeYear=$(date -d "-${i} month" +%Y);
        activeMonth=$(date -d "-${i} month" +%m);
            .log debug "Active year/month: ${activeYear}/$activeMonth";

        selectedYearMonth=($(echo "${sortedByYear[@]}" |  awk -F, -vyear="$activeYear" -vmonth="$activeMonth" 'BEGIN { RS = " " }; $1 == year && $2 == month { print $0 }'));
        numberOfElements=${#selectedYearMonth[@]};
        lastIndex=$(expr ${#selectedYearMonth[@]} - 1);
        
            .log debug "There are ${#selectedYearMonth[@]} elements";
            .log debug $(echo ${selectedYearMonth[@]} | tr " " "\n");

        if [[ ${numberOfElements} -gt 1 ]]; then
                .log debug  "Items to delete:\n";
                .log debug ${selectedYearMonth[@]:1:${lastIndex}} | tr " " "\n";
                .log info "Removing old $keyword files";
                rm $(echo ${selectedYearMonth[@]:1:${lastIndex}} | awk -F, 'BEGIN { RS = " " }; { print $5 }');

                .log debug "The remaining files:\n";    
                .log debug $(ls -lh ${path} | grep $keyword | grep ${activeYear} | grep ${activeMonth});

            else
                .log info "One file found per year/month, no additional files deleted";
                #echo "One file found per year/month, no additional files deleted";

        fi;

    done;
    
    fileCount=$(count_files $path $keyword);
    .log debug "Now there should be a maximum of ${maxMonths} $keyword files\n";
    .log info "Ending number of $keyword files: $fileCount";
    .log info "$(ls -lh ${path} | grep $keyword)";
    .log debug "Returning from monthly_rotation ()";
}

yearly_rotation() {

    # Remove files older than 5 years from a directory
    # For files younger that 5 years, remove all but the oldest file in that year
    #echo "";
    .log info "Starting yearly_rotation";

    path=$1

    keyword=yearly
   
    fileCount=$(count_files $path $keyword);
    
    .log info "Starting number of $keyword files: $fileCount";

    .log debug "$(ls -lh ${path} | grep yearly)";

    .log debug "Finding files older than $(expr 1825 / 365) years.";
    # 5 years equals 1825 days
    find ${path} -mtime +1825 -iname "*yearly*" -exec rm '{}' \;


    unsortedArray=($(find ${path} -iname "*yearly*" -printf "%TY,%Tm,%Td,%T@,%p\n"))
    sortedByYear=($(echo "${unsortedArray[@]}" | tr " " "\n" | sort | tr " " "\n"))

    activeYear=$currentYear

    while [[ $activeYear -gt $oldestYear ]]; do
        .log debug "The year is: $activeYear";

        selectedYear=($(echo "${sortedByYear[@]}" |  awk -F, -vyear="$activeYear" 'BEGIN { RS = " " }; $1 == year { print $0 }'));
        numberOfElements=${#selectedYear[@]};
        lastIndex=$(expr ${#selectedYear[@]} - 1);


            .log debug  "There are ${#selectedYear[@]} elements";
            .log debug $(echo ${selectedYear[@]} | tr " " "\n");

        if [[ ${numberOfElements} -gt 1 ]]; then
                .log debug "Items to delete:\n";
                .log debug $(echo ${selectedYear[@]:1:${lastIndex}} | tr " " "\n");
                .log info "Removing old $keyword files";

            rm $(echo ${selectedYear[@]:1:${lastIndex}} | awk -F, 'BEGIN { RS = " " }; { print $5 }');

                .log debug "Confirming the remaining files:\n";    
                .log debug $(ls -lh ${path} | grep ${activeYear});

            else
                .log debug "One file found per year. No additional files to delete.";
                #echo "One file found per year. No additional files to delete.";
        fi;
        let "activeYear -= 1";

    done;

    fileCount=$(count_files $path $keyword);
    .log debug "Now there should be a maximum of ${maxYears} ${keyword} files\n";
    .log info "Ending number of $keyword files: $fileCount";
    .log info "$(ls -lh ${path} | grep yearly)";
    .log debug "Returning from yearly_rotation ()";

}

pull_files () {
    # Retrieve backup files from remote servers
    # Copy and rename files 
    # 
    # Arguments: $1 -> path
    #            $2 -> server name
    #            $3  -> site name
    
    .log info "Beginning pull_files ()";
    path="${1}"; 
    serverName=${2};
    siteName=${3};
   
    .log debug "Pulling from ${serverName} ${siteName}";

    serverIP=${serverNameToIP[${serverName}]};
    serverUsername=${serverNameToUsername[$serverName]};
    .log debug "IP: ${serverIP}";

    srcFileNamePath="backups/${siteName}_backup${fileExtension}";
    .log info "Source file: ${srcFileNamePath}";

    destFilePathName="${path}${serverName}_${siteName}_${currentDate}${fileExtension}"
    .log info "Destination File: ${destFilePathName}";

    if [[ ${serverName} == "gd_prod_web_02" && ${siteName} == "cursos" ]]; then
        .log debug "Special action for ${serverName} ${siteName}";

        .log debug "Attemping to trigger the generate script on the far side";
         ssh ${serverUsername}@${serverIP} "nohup sh ./ammBackupScript/generateBackupFiles-gd-prod-cursos < /dev/null > ./ammBackupScript/scriptedBackup.log 2>&1 &";
	## The cursos site server finally using keys
        ## leaving the sshpass lines for a while just in case we have to revert
        #sshpass -f "${cursosFileNamePath}" ssh ${serverUsername}@${serverIP} "nohup sh ./ammBackupScript/generateBackupFiles-gd-prod-cursos < /dev/null > /ammBackupScript/scriptedBackup.log 2>&1 &";
        .log info "Resting ${sleepTime} while cursos script generates files"
        sleep ${sleepTime};

        .log debug "Running: sshpass -f ${cursosFileNamePath} scp ${serverUsername}@${serverIP}:${srcFileNamePath} ${destFilePathName}";
        scp ${serverUsername}@${serverIP}:${srcFileNamePath} ${destFilePathName};
        #sshpass -f${cursosFileNamePath} scp ${serverUsername}@${serverIP}:${srcFileNamePath} ${destFilePathName};

        else
            .log debug "Running: scp -i ${identityFilePath} ${serverUsername}@${serverIP}:${srcFileNamePath} ${destFilePathName}";
            scp -i ${identityFilePath} ${serverUsername}@${serverIP}:${srcFileNamePath} ${destFilePathName};
            results="${?}"
            .log debug "Results of the scp: ${results}";

            if [[ ${results} == 0 ]]; then
                .log info "scp exited without complaint";
            else
                .log error "ERROR: scp exited with ${results}. Something is wrong.";
            fi
    fi

    if ! [[ -e ${destFilePathName} ]]; then
        .log  error "\nERROR: scp failed. Possibly the backup file on destination not found NOT FOUND - ${destFilePathName}\n";
        #echo "scp failed. NOT FOUND - ${destFilePathName}";

        else
            .log debug "Creating daily|monthly|yearly files";

            keywordArray=(daily);
            
            if [[ "${currentMonth}${currentDay}" == 0101 ]]; then
                .log info "Happy New Year! Today is ${currentMonth}${currentDay}. Create yearly.";
                keywordArray+=("yearly");
            fi;
            
            if [[ "${currentDay}" == 01 ]]; then
                .log info "RabbitRabbit. Today is ${currentDay}st of the month. Create monthly.";
                keywordArray+=("monthly");
            fi;

            .log debug "Backup types to create: ${keywordArray[@]}";

            for keyword in ${keywordArray[@]}; do
                
                newFilePathName="${path}${serverName}_${siteName}_${keyword}_${currentDate}${fileExtension}"
                .log debug "Copying to: ${newFilePathName}";
                cp ${destFilePathName} ${newFilePathName} 
            done;

            fileCount=$(ls ${path} | wc -l);
           
            if [[ $test -ne 1 ]]; then 
                if [[ ${fileCount} -ge 2 ]]; then
                    .log debug "Removing ${destFilePathName}";
                    rm ${destFilePathName};

                    if [[ ${serverName} == "gd_prod_web_02" && ${siteName} == "cursos" ]]; then

                        .log debug "Attempting to rename the source file on ${serverName} to ${srcFileNamePath}_old";
                        ssh ${serverUsername}@${serverIP} "cp ${srcFileNamePath} ${srcFileNamePath}_old && rm ${srcFileNamePath}";
                        #sshpass -f${cursosFileNamePath} ssh ${serverUsername}@${serverIP} "cp ${srcFileNamePath} ${srcFileNamePath}_old && rm ${srcFileNamePath}";
                        results="${?}";
                        .log debug "Attempt results: ${results}";

                        else
         
                            .log debug "Attempting to rename the source file on the server to _old";
                            ssh -i ${identityFilePath} ${serverUsername}@${serverIP} "nohup cp ${srcFileNamePath} ${srcFileNamePath}_old < /dev/null >> ./copy_log 2>&1 && nohup rm ${srcFileNamePath} < /dev/null >> ./copy_log 2>&1";
                            results="${?}";
                            .log debug "Attempt results: ${?}";
                    fi
                fi
            else
                .log info "Testing flag found. Source files not removed/renamed."
            fi
    fi

    .log debug "Returning from pull_files ()";
}

execute_things () {
        serverName="${1}";
        siteName="${2}";
        path="${destDir}${serverName}/${siteName}/";

        .log info "******next site";
        
        .log debug "Beginning execute_things ()";
        .log info "Active site: ${siteName}";
        .log debug "Calling is_directory ()";
        is_directory ${path};

        .log info "Destination path: ${path}";

        if [[ ! -d ${path} ]]; then
            .log warn "Destination path: NOT FOUND.\nAttempting to create ${path}";
            mkdir -p ${path};
            results="${?}";
            if [[ $results != 0 ]]; then
                .log crit "FAILED: Could not create ${page}";
                exit 1;
            fi

        fi;
        
        .log debug "Calling pull_files ()";

        pull_files $path $serverName $siteName;

        .log debug "Calling daily_rotation ()";
        daily_rotation $path;
        
        if [[ ${currentDay} == 01 ]]; then 

            .log debug "Calling monthly_rotation ()";
             monthly_rotation $path;

            if [[ ${currentMonth} == 01 ]];  then

                .log debug "Calling yearly_rotation ()";
                yearly_rotation $path;
            
            fi;
        fi;

        .log debug "Returning from execute_things ()";
}

main () {
    # For server name, find the sites then execute the pull and rotation on each site
    .log debug "Beginning main ()";

    for i in ${srcServerNames[@]}; do
        serverName="${i}";
        .log info "****next server";
        .log info "Active server: ${serverName}";

        case ${serverName} in
            doweb01)
                for siteName in ${doweb01Sites[@]}; do
                    .log debug "Calling execute_things ()";
                    execute_things $serverName $siteName;
                done;
                ;;

            dev01)
                for siteName in ${dev01Sites[@]}; do
                    .log debug "Calling execute_things ()";
                    execute_things $serverName $siteName;
                done;
                ;;

            gd_prod_web_02) 
                for siteName in ${gd_prod_web_02Sites[@]}; do
                    .log debug "Calling execute_things ()";
                    execute_things $serverName $siteName;
                done;
                ;;

            lm) 
                for siteName in ${lmSites[@]}; do
                    .log debug "Calling execute_things ()";
                    execute_things $serverName $siteName;
                done;
                ;;

            amm_prod_web_01) 
                for siteName in ${amm_prod_web_01Sites[@]}; do
                    .log debug "Calling execute_things ()";
                    execute_things $serverName $siteName;
                done;
                ;;
            *)
                .log crit "main () :: received an invalid argument ${i}";
                exit 1;
                ;;

        esac
    done
    .log info "End of main ()";
}

main;

.log crit "End of script";
